### ISSUE TITLE
uncompatible with Retropie 3.0

### ISSUE THREAD

**Issue by Tsade** [rodrigosiviero/retropiesplashscreen#1]
Hi, 

Thanks for your work, but it is not compatible with retropie 3.0.
I think you have to change the path in splashscreen.sh from /home/pi/RetroPie-Setup/supplementary/splashscreens/\* to /opt/retropie/supplementary/splashscreen/*.
Regards,

**Comment by rodrigosiviero** [comment]
Hi!  I'll fix this asap thanks

**Comment by bistule** [comment]
still not working with Retropie 3.2.1

**Comment by rodrigosiviero** [comment]
Guys sorry for the delay I'm busy, I fixed the path with the one that @Tsade posted,  please let me know if it's working now,  I had to commit it by phone  :(

**Comment by rodrigosiviero** [comment]
Fixed!
