### ISSUE TITLE
Can't get this working

### ISSUE THREAD

**Issue by tomtordev** [rodrigosiviero/retropiesplashscreen#10]
Hi, i can't get this script working.

Can you help me?

What info/log do you need?

Thanks.

**Comment by rodrigosiviero** [comment]
Hi @torra87, please let me know retropie version, what steps are you doing to setup, check for the boot for any errors regarding the splashscreens.

Also, try to execute directly the splashscreen.sh multiple times and check between executions the content of the file: /etc/splashscreen.list

you may use: _**cat /etc/splashscreen.list**_

the content should change.

ps. be sure to execute with sudo the scripts

**Comment by tomtordev** [comment]
Hi @sur0x, i fixed it. I touch a lot of things, but i think the one it fix it was the retropie option "Enable Custom Splashscreen On Boot".

Thanks!

**Comment by rodrigosiviero** [comment]
Glad to hear!
