### ISSUE TITLE
Update Splashscreens

### ISSUE THREAD

**Issue by rodrigosiviero** [rodrigosiviero/retropiesplashscreen#3]
Gather splashs from the retropie forum.

Also I did the diff between the @taalas repository https://github.com/taalas/RetroPie-Artwork and I'll try to update with the splashs that he put together, hope it's OK!!! (please if you see this mention let me know!)

**Comment by rodrigosiviero** [comment]
Done, added 34 splashs

**Comment by taalas** [comment]
Sure, no problem. We (me and @herbfargus) started the RetroPie-Artwork repository to collect everything that is produced for RetroPie graphically. I am currently extremely busy (and sadly have been for a while) because of personal changes, but I hope to get back to it soon.

**Comment by rodrigosiviero** [comment]
Thanks @taalas !! Already updated, got more than 30 new splashs from your repo!! :)
