### ISSUE TITLE
New Option: Transfer videos 

### ISSUE THREAD

**Issue by rodrigosiviero** [rodrigosiviero/retropiesplashscreen#4]
Create an option to gather from another repository or mega url? splash videos posted on forum and install them.

**Comment by rodrigosiviero** [comment]
Hosting with Onedrive or other cloud would be good for transfer speed but terrible for versioning, so I'll be using bitbucket that has 2GB limit for files.

**Comment by rodrigosiviero** [comment]
videos uploaded to bitbucket, will implement the copy as soon as possible

**Comment by robertybob** [comment]
Sounds good!

**Comment by rodrigosiviero** [comment]
implemented with version 3.5
